INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Sheqer', '', '118');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Kos', '', '179');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Qumesht', '', '229');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Veze', '', '345');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Djath', '', '1499');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Vaj', '', '580');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Kripe', '', '69');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Salce', '', '319');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Vere', '', '4399');
INSERT INTO `products` (`id`, `name`, `description`, `price`) VALUES (NULL, 'Oriz', '', '359');

INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-07-06');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-08-05');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-08-18');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-10-19');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-11-09');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-11-18');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-12-10');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-12-15');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-12-29');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-01-28');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-02-07');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-04-19');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-04-29');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-06-21');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-06-22');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-06-28');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-07-25');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-09-12');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-09-16');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-10-13');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-11-10');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-11-15');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-12-23');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2023-01-02');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2023-01-18');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-08-09');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-09-27');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-10-26');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-12-10');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-01-06');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-01-24');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-04-05');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-04-08');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-04-18');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-04-19');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-05-30');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-06-09');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-06-13');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-07-05');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-07-15');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-07-27');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-08-11');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-08-25');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-08-26');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-09-15');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-09-16');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-09-21');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-10-06');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-11-17');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-12-07');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-07-02');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-07-27');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-08-23');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-09-03');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-09-09');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-10-08');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-11-10');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-11-17');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-11-18');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-11-26');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-12-03');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-12-13');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-12-27');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-01-19');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-01-20');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-03-02');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-05-05');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-05-13');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-08-29');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-09-09');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-10-05');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-10-14');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-11-16');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-11-29');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-12-19');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-07-14');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-08-11');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-09-06');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-09-13');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-09-22');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-10-11');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2021-12-01');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-01-05');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-01-14');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-01-21');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-02-23');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-03-30');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-04-14');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-04-18');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-05-12');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-05-20');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-06-24');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-06-30');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-08-26');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-09-13');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-10-12');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-12-12');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2022-12-23');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2023-01-06');
INSERT INTO `orders` (`id`, `name`, `date`) VALUES (NULL, NULL, '2023-01-13');

INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '1', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '1', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '2', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '2', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '3', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '3', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '3', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '3', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '3', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '4', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '5', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '6', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '6', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '6', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '6', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '7', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '7', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '7', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '7', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '7', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '8', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '8', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '8', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '8', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '9', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '9', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '9', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '9', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '9', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '10', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '10', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '10', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '11', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '12', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '12', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '13', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '13', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '14', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '14', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '14', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '14', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '15', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '15', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '15', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '15', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '16', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '16', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '17', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '17', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '17', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '18', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '18', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '18', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '19', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '19', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '19', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '19', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '20', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '20', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '20', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '21', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '21', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '22', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '22', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '22', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '23', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '23', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '23', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '23', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '23', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '24', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '24', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '24', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '24', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '24', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '25', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '25', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '25', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '26', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '27', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '27', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '28', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '28', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '29', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '29', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '29', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '30', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '30', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '30', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '30', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '31', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '32', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '32', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '33', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '33', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '34', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '34', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '34', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '35', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '35', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '36', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '36', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '36', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '36', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '37', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '37', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '37', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '37', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '38', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '38', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '38', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '39', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '39', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '39', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '39', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '40', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '40', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '40', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '41', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '41', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '42', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '42', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '42', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '42', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '43', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '43', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '44', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '44', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '44', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '44', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '44', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '45', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '45', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '45', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '45', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '46', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '46', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '46', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '46', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '47', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '47', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '47', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '47', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '47', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '48', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '48', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '48', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '48', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '48', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '49', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '49', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '49', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '49', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '49', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '50', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '50', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '50', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '51', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '52', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '52', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '52', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '53', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '53', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '53', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '53', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '54', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '54', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '55', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '55', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '55', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '55', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '56', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '56', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '57', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '57', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '58', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '58', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '58', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '58', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '58', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '59', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '59', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '59', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '59', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '59', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '60', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '60', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '60', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '60', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '61', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '62', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '63', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '64', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '64', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '64', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '65', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '65', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '65', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '65', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '66', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '66', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '66', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '66', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '67', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '67', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '68', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '69', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '69', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '69', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '69', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '70', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '70', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '70', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '70', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '70', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '71', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '71', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '71', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '72', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '72', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '72', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '72', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '73', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '73', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '74', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '74', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '74', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '74', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '74', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '75', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '75', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '75', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '75', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '75', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '76', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '76', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '76', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '76', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '77', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '78', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '78', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '78', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '78', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '79', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '80', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '80', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '81', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '81', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '81', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '82', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '83', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '84', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '84', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '84', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '84', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '84', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '85', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '85', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '85', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '85', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '86', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '86', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '87', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '88', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '88', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '88', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '89', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '89', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '89', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '89', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '90', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '90', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '91', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '91', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '91', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '91', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '91', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '92', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '93', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '93', '9');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '94', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '94', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '94', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '94', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '94', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '95', '1');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '96', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '96', '3');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '96', '7');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '96', '2');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '96', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '97', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '97', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '97', '6');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '2', '97', '5');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '98', '4');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '99', '8');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '3', '100', '10');
INSERT INTO `order_items` (`id`, `amount`, `order_id`, `product_id`) VALUES (NULL, '1', '100', '8');
